# Generated by Django 5.2.4 on 2025-07-06 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda_padrao', models.CharField(default='EUR', max_length=5)),
                ('idioma', models.CharField(default='pt', max_length=10)),
                ('frequencia_atualizacao', models.PositiveIntegerField(default=24)),
                ('meta_fire_total', models.DecimalField(decimal_places=2, default=600000, max_digits=12)),
                ('renda_fire_desejada', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
