# Generated by Django 5.2.4 on 2025-07-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('moeda', models.CharField(default='EUR', max_length=10)),
                ('frequencia_dividendos', models.CharField(default='trimestral', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=10)),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dividendos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asset')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('corretora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.broker')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
