# Generated by Django 5.2.4 on 2025-07-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='preco_atual',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='tipo',
            field=models.CharField(default='ativo', max_length=20),
        ),
    ]
